# Generated by Django 5.1.5 on 2025-02-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(choices=[('Trabalho', 'trabalho'), ('Pessoal', 'pessoal'), ('Estudo', 'estudo'), ('Outro', 'outro')], default='outro', max_length=15),
        ),
    ]
