# Generated by Django 5.1.5 on 2025-02-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(choices=[('Trabalho', 'Trabalho'), ('Pessoal', 'Pessoal'), ('Estudo', 'Estudo'), ('Outro', 'Outro')], max_length=15),
        ),
    ]
